### ISSUE TITLE
no acces at rspamd ui

### ISSUE THREAD

**Issue by steffaaannnn** [YunoHost-Apps/rspamd_ynh#2]
Hello 

Since the migration to debian bookworm, I no longer have access to the graphical interface on port 11334
how can I have access?

before the migration , i used the package for yunohost  rspamd-ui 

Best regards

**Comment by Caliandroid** [comment]
Hi @steffaaannnn -> Rspamd is not longer included into the yunohost core installation.
You can install it as a separate app package

From the yunohost12 announcement:
_The email antispam (Rspamd) and the XMPP server (Metronome) are not part of the core anymore. Instead, they have become separate applications_

Currently I cannot install rspamd successfully via the admin dashboard due to an error. I will open an issue in a few minutes.

**Comment by steffaaannnn** [comment]
Hi Caliandroid, 

I was able to install it, the service has been running correctly for several days, but I no longer have access to the graphical interface.

![image](https://github.com/user-attachments/assets/97b7e357-ba69-410d-9e3f-9bbfa3a916d3)

**Comment by Caliandroid** [comment]
Ok,
1. did you also install rspamdui as graphical user interface companion 
app?
https://apps.yunohost.org/app/rspamdui

2. Have you been able to install rspamd as yunohost app or did you 
install it on debian system level via apt install?

Thanks


Am 2024-11-08 07:05, schrieb steffaaannnn:

**Comment by Caliandroid** [comment]
Update: the rspamdui package is currently listed as "broken"
![Bildschirmfoto_2024-11-08_11-27-40](https://github.com/user-attachments/assets/dc2a8b78-8170-4b47-9509-93ab48f42aeb)

**Comment by steffaaannnn** [comment]
I install Rspamd and Rspamd web-ui and now , i think it'sok 

![image](https://github.com/user-attachments/assets/47248555-f6c9-4395-84af-273239de0520)

**Comment by steffaaannnn** [comment]
Hi , 

After install rspamd-ui ,  everything seems ok :-) 

![image](https://github.com/user-attachments/assets/29c80153-baba-4056-ba3f-0fff1b8b8715)

**Comment by alexAubin** [comment]
Bit confused but re-closing because apparently it does work ?
